
new function(){

	importPackage(java.lang) 
	importPackage(net.bleujin.searcher.search.filter)
	importPackage(net.bleujin.searcher.search.processor)  

	this.filter = function(){
		return new TermFilter("idx", "1") ;
	} 
	
	this.postProcessor = function(){
		return new net.bleujin.searcher.search.processor.PostProcessor({
			process : function(request, response){
				System.out.println(request + " "+ response) ;
			} 
		});
	} 
	
	this.handle = function(searcher){
		return searcher.andFilter(this.filter()).addPostListener(this.postProcessor()) ;
	}
} ;